
package View;

import Controller.BookController;
import Model.BooK;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class AdminBook extends javax.swing.JFrame {

    BookController b1 = new BookController();
    String bSearch;
    
    public AdminBook() {
        initComponents();
        b1.showOnTable(tblbook, bSearch);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BooK = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btnview = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBookYear = new javax.swing.JTextField();
        txtBookSearch = new javax.swing.JTextField();
        btndeleate = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbook = new javax.swing.JTable();
        txtBookName1 = new javax.swing.JTextField();
        lblsearch = new javax.swing.JLabel();
        txtAuthor1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(967, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BooK.setBackground(new java.awt.Color(204, 51, 0));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnview.setBackground(new java.awt.Color(204, 204, 0));
        btnview.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnview.setText("update");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jButton4.setText("ADD");

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Add BooK");

        javax.swing.GroupLayout BooKLayout = new javax.swing.GroupLayout(BooK);
        BooK.setLayout(BooKLayout);
        BooKLayout.setHorizontalGroup(
            BooKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BooKLayout.createSequentialGroup()
                .addGroup(BooKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BooKLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnview))
                    .addGroup(BooKLayout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(404, Short.MAX_VALUE))
            .addGroup(BooKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BooKLayout.createSequentialGroup()
                    .addContainerGap(804, Short.MAX_VALUE)
                    .addComponent(jButton4)
                    .addGap(86, 86, 86)))
        );
        BooKLayout.setVerticalGroup(
            BooKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BooKLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(168, 168, 168)
                .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BooKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BooKLayout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(107, Short.MAX_VALUE)))
        );

        getContentPane().add(BooK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 97));

        btnadd.setBackground(new java.awt.Color(153, 153, 0));
        btnadd.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 184, 156, -1));

        jLabel2.setBackground(new java.awt.Color(51, 0, 255));
        jLabel2.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText(" Name of BooK :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 0, 255));
        jLabel5.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Publisher year  :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel6.setBackground(new java.awt.Color(51, 0, 255));
        jLabel6.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Author :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        txtBookYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookYearActionPerformed(evt);
            }
        });
        getContentPane().add(txtBookYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 198, 30));

        txtBookSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtBookSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 198, 30));

        btndeleate.setBackground(new java.awt.Color(153, 153, 0));
        btndeleate.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btndeleate.setText("Deleate ");
        btndeleate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleateActionPerformed(evt);
            }
        });
        getContentPane().add(btndeleate, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 255, 156, -1));

        btnupdate.setBackground(new java.awt.Color(153, 153, 0));
        btnupdate.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnupdate.setText("update ");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 184, 156, -1));

        btnclear.setBackground(new java.awt.Color(153, 153, 0));
        btnclear.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnclear.setText("clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 255, 156, -1));

        tblbook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "bookID", "bookName", "Author", "pulished year"
            }
        ));
        tblbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbookMouseClicked(evt);
            }
        });
        tblbook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblbookKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblbook);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 437, 648, 240));

        txtBookName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookName1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtBookName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 196, 30));

        lblsearch.setBackground(new java.awt.Color(51, 0, 255));
        lblsearch.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        lblsearch.setForeground(new java.awt.Color(0, 0, 204));
        lblsearch.setText("serach :");
        getContentPane().add(lblsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        txtAuthor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthor1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtAuthor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 198, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        String Bname = txtBookName1.getText();
        String Bauther = txtBookSearch.getText();
        String Byear = txtBookYear.getText();

        BooK booKone = new BooK(Bname, Bauther, Byear);
        b1.addBook(booKone);
        //b1.OnTable(tblbook);
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtBookYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookYearActionPerformed

    private void txtBookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookSearchActionPerformed

    private void btndeleateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleateActionPerformed
            {                                           
            String td[] = b1.getDataFromtable(tblbook);
            int x = JOptionPane.showConfirmDialog(null, "Are you want to delete Book Details");

            if (x == 0) {
                b1.deleteBook(tblbook, bSearch, td);
                JOptionPane.showMessageDialog(null, "Book Details Delete successfully.");
                b1.showOnTable(tblbook, bSearch); // Refresh table data if necessary
                b1.textFieldClear(txtBookName1, txtBookSearch, txtBookYear);
            }
        } 
    }//GEN-LAST:event_btndeleateActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
    {                                            
            String btd[] = b1.getDataFromtable(tblbook);

            String name = txtBookName1.getText();
            String author = txtBookSearch.getText();
            String year = txtBookYear.getText();

            if (name.isEmpty() || author.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please Select, You Need to Update Row!");
            } else {
                BooK b = new BooK(name, author,year);
                b1.updateBookDetails(b, tblbook, bSearch, btd);
                b1.textFieldClear(txtBookName1, txtBookSearch,txtBookYear);
                b1.showOnTable(tblbook, bSearch);
            }
        }        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtBookName1.setText("");
        txtBookSearch.setText("");
        txtBookSearch.setText("");
        txtBookYear.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void tblbookKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblbookKeyReleased
       bSearch = txtBookSearch.getText();
       b1.searchBook(bSearch, bSearch, tblbook);
    }//GEN-LAST:event_tblbookKeyReleased

    private void tblbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbookMouseClicked
        String td[] = b1.getDataFromtable(tblbook);
        txtBookName1.setText(td[0]);
        txtBookSearch.setText(td[1]);
        txtBookYear.setText(td[2]);
    }//GEN-LAST:event_tblbookMouseClicked

    private void txtBookName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookName1ActionPerformed

    private void txtAuthor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BooK;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndeleate;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnview;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblsearch;
    private javax.swing.JTable tblbook;
    private javax.swing.JTextField txtAuthor1;
    private javax.swing.JTextField txtBookName1;
    private javax.swing.JTextField txtBookSearch;
    private javax.swing.JTextField txtBookYear;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
